name: 'workflow-status'
description: 'Github action to get the status of a workflow or a job on a given reference'
inputs:
  repo-token:
    description: 'Token for github-api calls'
    required: true

  ref:
    description: 'A git ref to be checked: branch/tag/commit sha. Defaults - current commit of started workflow'
    required: false

  workflow:
    description: 'The workflow name to get'
    required: true

  job:
    description: "The workflow's job to check (if not provided, the whole workflow state will be returned)"
    required: false

runs:
  using: 'node16'
  main: 'index.js'
