name: 'workflow-status'
description: 'Github action to get the status of a workflow or a job on a given reference'
inputs:
  repo-token:
    description: 'Token for github-api calls.'
    required: true

  workflow:
    description: 'The workflow file name to get (ex: tests.yml).'
    required: true

  head-sha:
    description: 'The full commit hash of the commit to be checked. Defaults to current commit of started workflow'
    required: false

runs:
  using: 'node16'
  main: 'index.js'
